// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// imp0clC
arma::mat imp0clC(const arma::mat X, arma::mat cls);
RcppExport SEXP _DrImpute_imp0clC(SEXP XSEXP, SEXP clsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cls(clsSEXP);
    rcpp_result_gen = Rcpp::wrap(imp0clC(X, cls));
    return rcpp_result_gen;
END_RCPP
}
// imp0clC2
arma::mat imp0clC2(const arma::mat X, arma::mat cls);
RcppExport SEXP _DrImpute_imp0clC2(SEXP XSEXP, SEXP clsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cls(clsSEXP);
    rcpp_result_gen = Rcpp::wrap(imp0clC2(X, cls));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DrImpute_imp0clC", (DL_FUNC) &_DrImpute_imp0clC, 2},
    {"_DrImpute_imp0clC2", (DL_FUNC) &_DrImpute_imp0clC2, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DrImpute(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
