# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

imp0clC <- function(X, cls) {
    .Call('_DrImpute_imp0clC', PACKAGE = 'DrImpute', X, cls)
}

imp0clC2 <- function(X, cls) {
    .Call('_DrImpute_imp0clC2', PACKAGE = 'DrImpute', X, cls)
}

